### ISSUE TITLE
Missing 5.11 data

### ISSUE THREAD

**Issue by sos0** [protopizza/ApIsOp#9]
Found so far:
- Caitlyn
- Jayce

**Comment by protopizza** [comment]
I don't understand why this is currently. Will fix other issues first...

**Comment by protopizza** [comment]
I believe it's highly possible Caitlyn and Jayce just may not have 5.11 data since they were both disabled during the patch. I'm not sure when they were re-enabled but it's possible their data set didn't include any matches with Caitlyn or Jayce. (Also that might be a good way for them to check if we're using the data validly...)

**Comment by protopizza** [comment]
Caitlyn was disabled due to a bug on her ult giving permanent vision on an enemy and Jayce's W not doing any damage. Sources: https://www.reddit.com/r/leagueoflegends/comments/399ni9/511_patch_bugs_megathread/cs21oj6 and https://www.reddit.com/r/leagueoflegends/comments/399ni9/511_patch_bugs_megathread/cs21smt

**Comment by sos0** [comment]
should add UI handling to account for this.

**Comment by protopizza** [comment]
+Tahm Kench in 5.11
